#!/usr/bin/perl

use lib "lib";
use lib "/usr/lib/perl5/site_perl/5.10.1";

use Getopt::ArgvFile
        home => 1,
        current => 1,
        resolveEnvVars => 1;
use Getopt::Long qw[:config permute bundling no_ignore_case no_auto_abbrev];
use Module::Package::RDF::Create;

my %options;

GetOptions(\%options,
	'abstract|A=s',
	'author|a=s%',
	'backpan=s',
	'copyright|c=s%',
	'destination|d=s',
	'help|usage|h',
	'licence_class|l=s',
	'use|M=s@',
	'version|v',
	);

if ($options{help} || !@ARGV)
{
	print <<'HELP'
mkdist [options] dist_name1 dist_name2 ...

Options:

  --abstract=S, -A=S       Short description for distribution
  --author k=v, -a k=v     Set author data.
  --backpan=S              URL for archives.
  --copyright k=v, -c k=v  Set copyright data.
  --destination=S, -d=S    Output directory.
  --help, -h               Show this help.
  --licence_class=S, -l=S  Perl class with licensing data.
  --use S, -M=S            Distribution should use these modules.
  --version=S, -v=S        Initial version number.

Author data keys:

  cpanid                Author's CPAN ID
  mbox                  Author's email address
  name                  Author's full name
  
Copyright data keys:

  holder                Copyright holder
  year                  Copyright year

The values of "use" are interpreted thusly:

  * 'common_sense' uses 'common::sense' instead of 'strict' and 'warnings'.
  * 'namespace_clean' uses 'namespace::clean'.
  * 'moose' (lowercase) uses 'Moose' and 'namespace::clean'.
  * '5.010' uses Perl 5.010, otherwise '5.008'.
  * Other values are interpreted as the names of modules to use.

license_class defaults to "Software::License::Perl_5".

Example:

  mkdist --author name="Toby Inkster" \
         --author cpanid="tobyink" \
         --copyright year=2010 \
         --abstract="does something useful" \
         --use common_sense \
         --use DateTime \
         "Local::Example::Useful"

Frequently used settings can be kept in ~/.mkdist

HELP
}

while (my $dist = shift @ARGV)
{
	Module::Package::RDF::Create->create($dist, %options);
}
